In [ ]:
print("Hello")

Hello


In [ ]:
# string manipulation

s = "hello"
print(s)
#print(s[2])
print(s[0], s[1], s[2], s[3], s[4])
print(s[-1], s[-2], s[-3], s[-4], s[-5])
print(len(s))
print(s+" world"+" am Sanchita")

hello
h e l l o
o l l e h
5
hello world am Sanchita


In [ ]:
# String is immutable

s='Hello'
print(s)
type(s)

s[1]="b"
print(s)

Hello


TypeError: ignored

In [ ]:
# String and integer

s = "hello"
num =10

print(s)
print(num)

print(s + str(num))

hello
10
hello10


In [ ]:
# String Methods

s="HelloTarif"
print(str.lower(s))
print(str.upper(s))
print(str.strip(s))
print(str.isalpha(s))
print(str.isdigit(s))
print(str.isspace(s))

hellotarif
HELLOTARIF
HelloTarif
True
False
False


In [ ]:
# String slice

s="hello"
print(s[1:3])
print("\n")

print(s[1:])
print("\n")

el


ello




In [ ]:
#String format

str1 = 'Hello %s, %d' %('world', 10)
print(str1)

str2 = 'Hello {}, {}'.format('world', 10)
print(str2)

str3 = 'Hello {wd}, {num}'.format(num=10, wd="world")
print(str3)

str4 = 'Hello {wd:10}, {num:.3f}'.format(num=10.0, wd="world")
print(str4)

Hello world, 10
Hello world, 10
Hello world, 10
Hello world     , 10.000


In [ ]:
# if statment

num=4
print(num)

if num < 5:print('num is smaller than 5')

if num>5: print('num is greater than 5')
elif num==5: print('num is 5')
else: print("num is smaller than 5")

4
num is smaller than 5
num is smaller than 5


In [ ]:
# Function call

print(type(32))
type(32)

print(int(32))

#print(int("hello"))
int(-2.3)

import math
print(math.sin(0.7))
print(math.cos(0.7))
print(math.tan(0.7))

print(math.acos(0.7))

print(math.sqrt(2))

help('math')

<class 'int'>
32
0.644217687237691
0.7648421872844885
0.8422883804630794
0.7953988301841436
1.4142135623730951
Help on built-in module math:

NAME
    math

DESCRIPTION
    This module provides access to the mathematical functions
    defined by the C standard.

FUNCTIONS
    acos(x, /)
        Return the arc cosine (measured in radians) of x.
        
        The result is between 0 and pi.
    
    acosh(x, /)
        Return the inverse hyperbolic cosine of x.
    
    asin(x, /)
        Return the arc sine (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    asinh(x, /)
        Return the inverse hyperbolic sine of x.
    
    atan(x, /)
        Return the arc tangent (measured in radians) of x.
        
        The result is between -pi/2 and pi/2.
    
    atan2(y, x, /)
        Return the arc tangent (measured in radians) of y/x.
        
        Unlike atan(y/x), the signs of both x and y are considered.
    
    atanh(x, /)
        Return 

In [ ]:
math.factorial(4)

24

In [ ]:
math.exp(2)

7.38905609893065

In [ ]:
math.floor(2)

2

In [ ]:
math.gcd(4)

4

In [ ]:
math.isfinite(999)

True

In [ ]:
# Function
def print_name():
  print("am Sanchita")

print_name()

am Sanchita


In [ ]:
def print_twice(arg1):
  print(arg1)

print_twice(math.pi)
print_twice(math.cos(math.pi))

print_twice('Spam'*4)

3.141592653589793
-1.0
SpamSpamSpamSpam


In [ ]:
result = print_twice('Bing')
print(result)

Bing
None


In [ ]:
def print_twice(arg1, arg2):
  return arg1,arg2

res1, res2 = print_twice('Bing', "San")
print(res1)
print(res2)

Bing
San


In [ ]:
# Function checking factorial

def factorial(n):
  if not isinstance(n, int):
    print("Factorial is only defined for integers")
    return None
  elif n < 0:
    print("Factorial is not defined for negative numbers")
  elif n==0:
    return 1
  else:
    return n*factorial(n-1)

factorial(-3)

Factorial is not defined for negative numbers


In [ ]:
# Function Overloading

def func1(arg1, arg2=None):
  if arg2 is None:
    print(arg1)
  else:
    print(arg1, arg2)

func1('hello', 10)

hello 10


In [ ]:
## Global / Local Variable

global_var = 1

def func1():
  global global_var
  global_var = 2

func1()
global_var

2

In [ ]:
var=1

def func1():
  var=2

func1()
var


1

## Ex2

In [ ]:
import math

a=2
b=5

c=(a**2 + b**2)**(0.5)
d=math.sqrt(c)
print('Hypo c=',c)
print('sq root d=', d)

print("c*d=", c*d)
print("c/d=", c/d)
print("a*sin(b)=", (a*math.sin(b)))
print("factorial(d)=", factorial(int(d)))

e=math.log(d)
print("e=",e)

Hypo c= 5.385164807134504
sq root d= 2.320595787106084
c*d= 12.496790764308276
c/d= 2.3205957871060834
a*sin(b)= -1.917848549326277
factorial(d)= 2
e= 0.8418239574966185


In [ ]:
# Matrices

from scipy import *
from numpy import *

M1 = array([[1,2,3], [3,4,5],[1,2,1]])
M2=array([[0,1,2], [3,4,5],[7,8,2]])

M3=M1*M2

print('\n M1 = ', M1)
print('\n M2 = ', M2)
print('\n M3 = ', M3)
#print(M1.I)


 M1 =  [[1 2 3]
 [3 4 5]
 [1 2 1]]

 M2 =  [[0 1 2]
 [3 4 5]
 [7 8 2]]

 M3 =  [[ 0  2  6]
 [ 9 16 25]
 [ 7 16  2]]


In [ ]:
# Create vector
from numpy import matrix

M1=matrix([[1,2,3], [3,4,5],[1,2,1]])
M2=matrix([[0,1,2], [3,4,5],[7,8,2]])

print(M1*M2)
print(M1.T)
print(M1.I)

[[27 33 18]
 [47 59 36]
 [13 17 14]]
[[1 3 1]
 [2 4 2]
 [3 5 1]]
[[-1.5  1.  -0.5]
 [ 0.5 -0.5  1. ]
 [ 0.5 -0.  -0.5]]
